apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx-lease-rbac.yaml
  - goldilocks.yaml
  - local-path-provisioner.yaml
  - cert-manager.yaml
  - metrics-server.yaml
